server:
  port: 8761
spring:
  jmx:
    enabled: false
eureka:
  server:
    #心跳正常客户端百分比阈值
    renewal-percent-threshold: 0.85
    #自我保护机制，默认开启-true
    enable-self-preservation: true
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://centos-p160:${server.port}/eureka-server/eureka,http://centos-p161:${server.port}/eureka-server/eureka,http://centos-p162:${server.port}/eureka-server/eureka